---
- name: Pull the latest code
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    version: main

- name: Install npm dependencies
  command: pnpm i -D
  args:
    chdir: "{{ app_path }}"
  become_user: linuxuser

- name: Build the application
  command: pnpm run build
  args:
    chdir: "{{ app_path }}"
  become_user: linuxuser
  
- name: Remove dev dependencies
  command: pnpm i -P
  args:
    chdir: "{{ app_path }}"
  become_user: linuxuser
    
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    mode: 0644

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Start the application with PM2
  command: pm2 restart all
  args:
    chdir: "{{ app_path }}"
  ignore_errors: yes
  become_user: linuxuser

- name: Save PM2 process list
  command: pm2 save
  become_user: linuxuser

